version: '3'

services:
  mysql_master:
    image: mysql:latest
    container_name: mysql_master
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3306:3306"

  mysql_slave:
    image: mysql:latest
    container_name: mysql_slave
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: "mysql_master,mysql_slave"
      PMA_ARBITRARY: 1 #Esta variable se utiliza para especificar los hosts de MySQL a los que phpMyAdmin puede conectarse.
    depends_on:
      - mysql_master #Especifica que este servicio depende de los servicios mysql_master y mysql_slave.
      - mysql_slave
    ports:
      - "8080:80"
